# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_time', models.DateTimeField(auto_now=True)),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_context', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('reading_volume', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_configure_image')),
            ],
        ),
    ]
