# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-11 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_label',
            field=models.CharField(default='nginx', max_length=20),
        ),
    ]
