# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181211_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_context',
            field=models.TextField(max_length=1000),
        ),
    ]
