# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181211_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
