# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181212_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
